---
title: "Shielded individuals and their mental health in Wales"
author: "Jiao Song, Alisha Davies on behalf of NDL Wales"
date: "12/03/2021"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Background and research questions
Whilst there is some work underway exploring the impact of COVID-19 on presentations to health care services with mental health related issues in Wales, a focus on depression and anxiety of people who were shielding is lacking. Feeling raised levels of anxiety since the COVID-19 pandemic was commonly reported with a marked increase at the beginning of lockdown. 37% of adults in the UK were reporting high levels of anxiety in May 2020^[https://www.ons.gov.uk/peoplepopulationandcommunity/wellbeing/articles/coronavirusandanxietygreatbritain/3april2020to10may2020]. One in five adults in the UK were likely to experience depression during the pandemic^[https://www.ons.gov.uk/peoplepopulationandcommunity/wellbeing/articles/coronavirusanddepressioninadultsgreatbritain/june2020]. One study suggests that 35% of the shielded people reported worsening mental health since the shielding guidance but differ by age and gender ^[https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/bulletins/coronavirusandshieldingofclinicallyextremelyvulnerablepeopleinengland/28mayto3june2020]. There is less evidence of the impact on depression and anxiety for those who were shielding in Wales. 

>**Research question one:** For shielded individuals, what factors were associated with increased risk of developing anxiety and depression conditions during shielding? 

>**Research question two:** Was shielding associated with increased risk of developing anxiety and depression conditions?

## Methods

- Shielded group:  all shielded individuals on Shielded Patient List (SPL) meeting the inclusion and exclusion criteria described in the centralised analysis^[https://www.health.org.uk/news-and-comment/charts-and-infographics/exploring-demographic-variation-in-groups-advised-to-shield].

- Control group:  a randomly selected group of residents in Wales who were not shielding and registered in one of the GPs that shielded ones were registered with on 01/03/2020.

- Study period: from 01/03/2018 to 31/10/2020. It covers 01/03/2018 to 29/02/2020, and 01/03/2020 to 31/10/2020 corresponding to before and during shielding. 

- The outcome of interest: depression and anxiety conditions during shielding. We included symptoms, diagnosis and prescriptions of depression and/or anxiety identified using READ codes^[https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-016-0274-7]. 

- A history of depression and/or anxiety is defined as whether any symptoms, diagnosis or prescriptions were recorded between 01/03/2018 and 29/02/2020.

- We used logistic regression modelling to understand the effect size of factors of interest. 

## Data and linkages

Data linkage and analysis were conducted within SAIL Gateway^[https://saildatabank.com/].

>**Research question one:** We linked Shielded Patient List (SPL) with primary care general practice dataset available in SAIL Databank to obtain information symptoms, diagnosis and prescriptions of depression and anxiety. 

>**Research question two:** We linked the control group with Welsh Demographic Service dataset to obtain information on gender, age, deprivation and urban/rural residency. We then linked the control group with primary care general practice dataset available in SAIL Databank to obtain information symptoms, diagnosis and prescriptions of depression and anxiety. 

We indicated all individuals in both shielded and control groups with at least one symptom, diagnosis or prescription record regarding to depression and/or anxiety during the study period.

## Cohort

>**Shielded group:** There are 128,690 individuals and the characteristic description is available in the centralised analysis^[https://www.health.org.uk/news-and-comment/charts-and-infographics/exploring-demographic-variation-in-groups-advised-to-shield].


>**Control group:** There are 128,690 individuals. Comparing with the control groups, the shielded group is with more female (53.4% vs 50.0%), older age groups (60-69 22.7% vs 11.5%, 70-79 26.3% vs 9.1%, 80+ 13.8% vs 6.1%), living in most deprived areas (21.7% vs 16.8%), urban area residents (68.1% vs 62.8%), with depression and/or anxiety history (9.1% vs 2.3%) and with depression and/or anxiety during shielding (2.2% vs 0.5%). 

## Results

* **Research question one:** Factors associated with increased risk of developing anxiety and depression conditions during shielding


    +	Female (odds ratio 1.4, 95% CI 1.3-1.6)

    + 20-29 years old (1.7, 1.3-2.1), 30-39 years old (1.4, 1.2-1.8)

    + History of depression and/or anxiety (6.7, 6.1-7.2)

We didn’t observe any statistically significant differences across reasons for shielding apart from renal dialysis which can be a result of small sample size.  

* **Research question two:**  Was shielding associated with increased risk of developing anxiety and depression conditions? Yes and also other factors.

    +	Female (odds ratio 1.4, 95% CI 1.3-1.5)
    
    + 20-29 years old (2.2, 1.9-2.7), 30-39 years old (1.8, 1.5-2.1), 40-49 years old (1.3, 1.0-1.5), 50-59 years old (1.2, 1.0-1.4)
    
    + Urban area residents (1.1, 1.0-1.2)
    
    + History of depression and/or anxiety (8.5, 7.9-9.2)
    
    + Shielding (3.6, 3.3-4.0) 

This is a piece of rapid analysis to understand the depression and anxiety conditions for shielded patients in Wales. There were a number of limitations for the study including incomplete control of confounders. 
    

**NDL Wales Membership:** Dr Alisha Davies (Head of Research and Development, Public Health Wales); Dr Jiao Song (Principle Statistician, Public Health Wales); Tomos Smith (Senior Research Officer, Public Health Wales);  Laura Bentley (Research Officer, Public Health Wales); Ashley Akbari (Swansea University); Paul Howell (NWIS -National Data Resource); Gareth Johns (NWIS); Lisa Trigg (Social Care Wales); Joanna Dundon (NWIS – Digital Services for Patients and Public);  Lynsey Cross (Swansea University); Bethan Carter (Senior Research Officer, Public Health Wales); David Florentin (Senior Research Officer, Public Health Wales); Claire Newman (Swansea University); Simon Thompson (Swansea University).


**Ethics statement:** This study is based on anonymised routinely collected electronic health records. All routinely collected anonymised data held in SAIL Databank are exempt from consent due to the anonymised nature of the databank (under section 251, National Research Ethics Committee (NREC)). We have applied and been granted approval by the independent Information Governance Review Panel (IGRP) for permission to conduct this study (project number 1224). The IGRP contains independent members from NREC and British Medical Association (BMA), as well as lay members. The review process has checked that the study is useful, not service evaluation, and will not break anonymisation standards.
